---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-postgresdemo
  namespace: mfi-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-postgresdemo
  template:
    metadata:
      labels:
        app: deploy-postgresdemo
    spec:
      containers:
      - name: deploy-postgresdemo
        image:  postgres:9.6 
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "keycloak"
        - name: POSTGRES_USER
          value: "keycloak"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: POSTGRES_DATABASE
          value: keycloak
        - name: POSTGRES_ROOT_PASSWORD
          value: password
---
apiVersion: v1
kind: Service
metadata: 
  name: postgresdemo
  namespace: mfi-dev
spec: 
  selector: 
    app: deploy-postgresdemo
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP  
  type: ClusterIP
